#!/bin/bash

mkdir build

{
  cd build || exit
  cmake -DCMAKE_BUILD_TYPE=Release ..
  cmake --build .
  cpack -G DEB
}

# This user was added in docker build, do this so we can access files outside container
chown -R user:user _packages
mkdir deploy
mv _packages/* deploy/