#!/bin/bash

mkdir build
cd build
cmake -DCMAKE_BUILD_TYPE=Release ..
make -j$(nproc)
make install
# This user was added in docker build, do this so we can access files outside container
chown -R user:user build