FROM ubuntu:20.04

ENV DEBIAN_FRONTEND noninteractive

RUN apt-get update && \
    apt-get install -y software-properties-common && \
    add-apt-repository -y ppa:ubuntugis/ppa && \
      apt-get -y update && \
      apt-get install -y --no-install-recommends \
                    build-essential \
                    ca-certificates \
                    cmake \
                    doxygen \
                    g++ \
                    git \
                    libeigen3-dev \
                    libgdal-dev \
                    libpython3-dev \
                    python3 \
                    python3-pip \
                    python3-matplotlib \
                    lcov \
                    libgtest-dev \
                    && \
                    apt-get autoclean && \
                    apt-get autoremove && \
                    apt-get clean && \
                    rm -rf /var/lib/apt/lists/*

RUN python3 -m pip install gcovr